export ODEV_NAME="stm32mp1"
export OEDEV_DOCKER_YOCTO_IMG=crops/stm32mp15:ubuntu-22.04
export OEDEV_META_ROOT=$HOME/personal/stm32mp1/meta
export OEDEV_META_SHARED_DOWLOADS_HOST=$OEDEV_META_ROOT/shared-downloads
export OEDEV_WORKDIR_HOST=$OEDEV_META_ROOT
export OEDEV_WORKDIR_CONTAINER=/oedev-container-$ODEV_NAME
export OEDEV_META_SHARED_DOWLOADS_CONTAINER=$OEDEV_WORKDIR_CONTAINER/shared-downloads

